import 'dotenv/config';

import { PrismaPg } from '@prisma/adapter-pg';

import { PrismaClient } from '../src/generated/prisma/client';

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error('DATABASE_URL is missing in .env file');
}

const adapter = new PrismaPg({
  connectionString: databaseUrl,
});

const prisma = new PrismaClient({
  adapter,
});

const sriLankanProvinces = [
  { name: 'Central', code: 'CENTRAL', displayOrder: 1 },
  { name: 'Eastern', code: 'EASTERN', displayOrder: 2 },
  { name: 'Northern', code: 'NORTHERN', displayOrder: 3 },
  { name: 'North Central', code: 'NORTH_CENTRAL', displayOrder: 4 },
  { name: 'North Western', code: 'NORTH_WESTERN', displayOrder: 5 },
  { name: 'Sabaragamuwa', code: 'SABARAGAMUWA', displayOrder: 6 },
  { name: 'Southern', code: 'SOUTHERN', displayOrder: 7 },
  { name: 'Uva', code: 'UVA', displayOrder: 8 },
  { name: 'Western', code: 'WESTERN', displayOrder: 9 },
] as const;

const sriLankanDistricts = [
  { name: 'Kandy', code: 'KANDY', provinceCode: 'CENTRAL', displayOrder: 1 },
  { name: 'Matale', code: 'MATALE', provinceCode: 'CENTRAL', displayOrder: 2 },
  {
    name: 'Nuwara Eliya',
    code: 'NUWARA_ELIYA',
    provinceCode: 'CENTRAL',
    displayOrder: 3,
  },
  { name: 'Ampara', code: 'AMPARA', provinceCode: 'EASTERN', displayOrder: 1 },
  {
    name: 'Batticaloa',
    code: 'BATTICALOA',
    provinceCode: 'EASTERN',
    displayOrder: 2,
  },
  {
    name: 'Trincomalee',
    code: 'TRINCOMALEE',
    provinceCode: 'EASTERN',
    displayOrder: 3,
  },
  { name: 'Jaffna', code: 'JAFFNA', provinceCode: 'NORTHERN', displayOrder: 1 },
  {
    name: 'Kilinochchi',
    code: 'KILINOCHCHI',
    provinceCode: 'NORTHERN',
    displayOrder: 2,
  },
  { name: 'Mannar', code: 'MANNAR', provinceCode: 'NORTHERN', displayOrder: 3 },
  {
    name: 'Mullaitivu',
    code: 'MULLAITIVU',
    provinceCode: 'NORTHERN',
    displayOrder: 4,
  },
  {
    name: 'Vavuniya',
    code: 'VAVUNIYA',
    provinceCode: 'NORTHERN',
    displayOrder: 5,
  },
  {
    name: 'Anuradhapura',
    code: 'ANURADHAPURA',
    provinceCode: 'NORTH_CENTRAL',
    displayOrder: 1,
  },
  {
    name: 'Polonnaruwa',
    code: 'POLONNARUWA',
    provinceCode: 'NORTH_CENTRAL',
    displayOrder: 2,
  },
  {
    name: 'Kurunegala',
    code: 'KURUNEGALA',
    provinceCode: 'NORTH_WESTERN',
    displayOrder: 1,
  },
  {
    name: 'Puttalam',
    code: 'PUTTALAM',
    provinceCode: 'NORTH_WESTERN',
    displayOrder: 2,
  },
  {
    name: 'Kegalle',
    code: 'KEGALLE',
    provinceCode: 'SABARAGAMUWA',
    displayOrder: 1,
  },
  {
    name: 'Ratnapura',
    code: 'RATNAPURA',
    provinceCode: 'SABARAGAMUWA',
    displayOrder: 2,
  },
  { name: 'Galle', code: 'GALLE', provinceCode: 'SOUTHERN', displayOrder: 1 },
  {
    name: 'Hambantota',
    code: 'HAMBANTOTA',
    provinceCode: 'SOUTHERN',
    displayOrder: 2,
  },
  { name: 'Matara', code: 'MATARA', provinceCode: 'SOUTHERN', displayOrder: 3 },
  { name: 'Badulla', code: 'BADULLA', provinceCode: 'UVA', displayOrder: 1 },
  {
    name: 'Monaragala',
    code: 'MONARAGALA',
    provinceCode: 'UVA',
    displayOrder: 2,
  },
  {
    name: 'Colombo',
    code: 'COLOMBO',
    provinceCode: 'WESTERN',
    displayOrder: 1,
  },
  {
    name: 'Gampaha',
    code: 'GAMPAHA',
    provinceCode: 'WESTERN',
    displayOrder: 2,
  },
  {
    name: 'Kalutara',
    code: 'KALUTARA',
    provinceCode: 'WESTERN',
    displayOrder: 3,
  },
] as const;

function toCityCode(districtCode: string, cityName: string) {
  return `${districtCode}_${cityName
    .replace(/['’]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase()}`;
}

function createCities(districtCode: string, names: readonly string[]) {
  return names.map((name, index) => ({
    name,
    code: toCityCode(districtCode, name),
    districtCode,
    displayOrder: index + 1,
  }));
}

const sriLankanCities = [
  ...createCities('COLOMBO', [
    'Colombo',
    'Dehiwala',
    'Mount Lavinia',
    'Moratuwa',
    'Sri Jayawardenepura Kotte',
    'Nugegoda',
    'Maharagama',
    'Kottawa',
    'Homagama',
    'Piliyandala',
    'Kesbewa',
    'Boralesgamuwa',
    'Battaramulla',
    'Rajagiriya',
    'Kolonnawa',
    'Kaduwela',
    'Malabe',
    'Athurugiriya',
    'Padukka',
    'Hanwella',
    'Avissawella',
    'Wellawatte',
    'Bambalapitiya',
    'Kollupitiya',
    'Borella',
    'Narahenpita',
    'Kirulapone',
    'Thimbirigasyaya',
    'Havelock Town',
    'Cinnamon Gardens',
    'Slave Island',
    'Kotahena',
    'Grandpass',
    'Mattakkuliya',
    'Ratmalana',
    'Angoda',
    'Gothatuwa',
    'Mulleriyawa',
    'Kosgama',
    'Meegoda',
    'Bokundara',
  ]),

  ...createCities('GAMPAHA', [
    'Gampaha',
    'Negombo',
    'Wattala',
    'Ja-Ela',
    'Kandana',
    'Ragama',
    'Kadawatha',
    'Kiribathgoda',
    'Kelaniya',
    'Biyagama',
    'Sapugaskanda',
    'Minuwangoda',
    'Divulapitiya',
    'Mirigama',
    'Nittambuwa',
    'Veyangoda',
    'Ganemulla',
    'Seeduwa',
    'Katunayake',
    'Raddoluwa',
    'Yakkala',
    'Udugampola',
    'Ekala',
    'Mabole',
    'Uswetakeiyawa',
    'Pamunugama',
    'Delgoda',
    'Dompe',
    'Dekatana',
    'Kirindiwela',
    'Pugoda',
    'Weliweriya',
    'Mahara',
    'Makola',
    'Peliyagoda',
    'Heiyanthuduwa',
    'Hunupitiya',
    'Kotugoda',
    'Andiambalama',
  ]),

  ...createCities('KALUTARA', [
    'Kalutara',
    'Panadura',
    'Horana',
    'Bandaragama',
    'Beruwala',
    'Aluthgama',
    'Matugama',
    'Agalawatta',
    'Bulathsinhala',
    'Dodangoda',
    'Ingiriya',
    'Wadduwa',
    'Payagala',
    'Maggona',
    'Dharga Town',
    'Katukurunda',
    'Nagoda',
    'Morontuduwa',
    'Millaniya',
    'Neboda',
    'Thebuwana',
    'Meegahatenna',
    'Walallawita',
    'Bellana',
    'Ittapana',
    'Pelawatta',
    'Yatadolawatta',
  ]),

  ...createCities('KANDY', [
    'Kandy',
    'Peradeniya',
    'Katugastota',
    'Gampola',
    'Nawalapitiya',
    'Kadugannawa',
    'Pilimathalawa',
    'Wattegama',
    'Akurana',
    'Digana',
    'Kundasale',
    'Teldeniya',
    'Galagedara',
    'Ampitiya',
    'Menikhinna',
    'Poojapitiya',
    'Panwila',
    'Madawala Bazaar',
    'Galaha',
    'Hindagala',
    'Ankumbura',
    'Hataraliyadda',
    'Udadumbara',
    'Hasalaka',
    'Madugalla',
    'Thalatuoya',
    'Daulagala',
    'Gelioya',
  ]),

  ...createCities('MATALE', [
    'Matale',
    'Dambulla',
    'Sigiriya',
    'Galewela',
    'Rattota',
    'Ukuwela',
    'Naula',
    'Pallepola',
    'Yatawatta',
    'Laggala',
    'Wilgamuwa',
    'Aluvihare',
    'Elkaduwa',
    'Kaikawala',
    'Kibissa',
    'Palapathwela',
    'Madawala Ulpotha',
    'Opalgala',
    'Wahacotte',
    'Lenadora',
    'Dewahuwa',
    'Muwandeniya',
    'Handungamuwa',
    'Nalanda',
  ]),

  ...createCities('NUWARA_ELIYA', [
    'Nuwara Eliya',
    'Hatton',
    'Talawakele',
    'Kotagala',
    'Lindula',
    'Nanu Oya',
    'Ragala',
    'Walapane',
    'Hanguranketha',
    'Pundaluoya',
    'Ginigathena',
    'Maskeliya',
    'Kotmale',
    'Pussellawa',
    'Ramboda',
    'Labukele',
    'Kandapola',
    'Uda Pussellawa',
    'Ambewela',
    'Pattipola',
    'Nildandahinna',
    'Rikillagaskada',
    'Agarapathana',
    'Bogawantalawa',
    'Dickoya',
    'Norwood',
    'Watawala',
    'Rozella',
  ]),

  ...createCities('GALLE', [
    'Galle',
    'Hikkaduwa',
    'Ambalangoda',
    'Elpitiya',
    'Baddegama',
    'Karapitiya',
    'Ahangama',
    'Unawatuna',
    'Bentota',
    'Balapitiya',
    'Batapola',
    'Imaduwa',
    'Yakkalamulla',
    'Neluwa',
    'Akkmeemana',
    'Boossa',
    'Gintota',
    'Koggala',
    'Talpe',
    'Habaraduwa',
    'Udugama',
    'Karandeniya',
    'Gonapinuwala',
    'Wakwella',
    'Poddala',
    'Pinnaduwa',
    'Wanduramba',
    'Thawalama',
  ]),

  ...createCities('MATARA', [
    'Matara',
    'Weligama',
    'Akuressa',
    'Deniyaya',
    'Hakmana',
    'Kamburupitiya',
    'Dikwella',
    'Devinuwara',
    'Gandara',
    'Pitabeddara',
    'Morawaka',
    'Athuraliya',
    'Mirissa',
    'Kekanadura',
    'Thihagoda',
    'Malimbada',
    'Kirinda Puhulwella',
    'Pasgoda',
    'Urubokka',
    'Kotapola',
    'Makandura',
    'Welipitiya',
    'Kottegoda',
    'Thalpawila',
  ]),

  ...createCities('HAMBANTOTA', [
    'Hambantota',
    'Tangalle',
    'Tissamaharama',
    'Beliatta',
    'Ambalantota',
    'Weeraketiya',
    'Sooriyawewa',
    'Lunugamvehera',
    'Walasmulla',
    'Middeniya',
    'Weerawila',
    'Kirinda',
    'Ranna',
    'Hungama',
    'Nonagama',
    'Agunukolapelessa',
    'Katuwana',
    'Mulkirigala',
    'Barawakumbuka',
    'Debarawewa',
  ]),

  ...createCities('JAFFNA', [
    'Jaffna',
    'Nallur',
    'Chavakachcheri',
    'Point Pedro',
    'Valvettithurai',
    'Kopay',
    'Tellippalai',
    'Manipay',
    'Karainagar',
    'Kayts',
    'Velanai',
    'Delft',
    'Chunnakam',
    'Kankesanthurai',
    'Chankanai',
    'Vaddukoddai',
    'Uduvil',
    'Achchuvely',
    'Sandilipay',
    'Chulipuram',
    'Puttur',
    'Navaly',
    'Kokuvil',
    'Inuvil',
    'Urumpirai',
    'Araly',
    'Pungudutivu',
    'Mandaitivu',
    'Eluvaitivu',
  ]),

  ...createCities('KILINOCHCHI', [
    'Kilinochchi',
    'Pallai',
    'Paranthan',
    'Poonakary',
    'Kandavalai',
    'Dharmapuram',
    'Akkarayankulam',
    'Iranamadu',
    'Mulankavil',
    'Vaddakachchi',
    'Kilali',
    'Uruthirapuram',
    'Jayapuram',
    'Elephant Pass',
    'Kanakapuram',
  ]),

  ...createCities('MANNAR', [
    'Mannar',
    'Murunkan',
    'Nanattan',
    'Pesalai',
    'Talaimannar',
    'Adampan',
    'Madhu',
    'Silavathurai',
    'Thalaimannar Pier',
    'Erukkalampiddy',
    'Vankalai',
    'Vidataltivu',
    'Uyilankulam',
    'Periyakadai',
    'Pallimunai',
    'Musali',
    'Arippu',
    'Periyamadhu',
    'Iluppaikadavai',
  ]),

  ...createCities('MULLAITIVU', [
    'Mullaitivu',
    'Puthukudiyiruppu',
    'Oddusuddan',
    'Mankulam',
    'Mallavi',
    'Maritimepattu',
    'Thunukkai',
    'Mulliyawalai',
    'Kokkilai',
    'Kokuthoduvai',
    'Alampil',
    'Nayaru',
    'Kumulamunai',
    'Vattappalai',
    'Visuvamadu',
    'Udayarkattu',
  ]),

  ...createCities('VAVUNIYA', [
    'Vavuniya',
    'Cheddikulam',
    'Nedunkeni',
    'Omanthai',
    'Puliyankulam',
    'Settikulam',
    'Poovarasankulam',
    'Maharambaikulam',
    'Nelukkulam',
    'Thandikulam',
    'Mamaduwa',
    'Kurumankadu',
    'Irambaikulam',
    'Pambaimadu',
    'Kovilkulam',
    'Neriyakulam',
    'Kanagarayankulam',
    'Pavatkulam',
  ]),

  ...createCities('AMPARA', [
    'Ampara',
    'Kalmunai',
    'Akkaraipattu',
    'Sammanthurai',
    'Sainthamaruthu',
    'Pottuvil',
    'Dehiattakandiya',
    'Maha Oya',
    'Uhana',
    'Damana',
    'Lahugala',
    'Addalaichenai',
    'Nintavur',
    'Maruthamunai',
    'Thirukkovil',
    'Alayadivembu',
    'Irakkamam',
    'Oluvil',
    'Palamunai',
    'Karaitivu',
    'Chavalakade',
    'Navithanveli',
    'Malwatta',
    'Central Camp',
    'Hingurana',
  ]),

  ...createCities('BATTICALOA', [
    'Batticaloa',
    'Eravur',
    'Kattankudy',
    'Valachchenai',
    'Kalkudah',
    'Vakarai',
    'Chenkalady',
    'Kaluwanchikudy',
    'Arayampathy',
    'Oddamavadi',
    'Paddiruppu',
    'Vellavely',
    'Kokkadicholai',
    'Kiran',
    'Mankerni',
    'Puliyanthivu',
    'Navatkudah',
    'Thannamunai',
    'Vantharumoolai',
    'Cheddipalayam',
    'Manmunai',
  ]),

  ...createCities('TRINCOMALEE', [
    'Trincomalee',
    'Kinniya',
    'Muttur',
    'Kantale',
    'China Bay',
    'Nilaveli',
    'Uppuveli',
    'Thambalagamuwa',
    'Seruwila',
    'Gomarankadawala',
    'Kuchchaveli',
    'Pulmoddai',
    'Morawewa',
    'Padavi Sri Pura',
    'Sampur',
    'Verugal',
    'Agbopura',
    'Somapura',
    'Ichchilampattai',
    'Mollipothana',
  ]),

  ...createCities('ANURADHAPURA', [
    'Anuradhapura',
    'Kekirawa',
    'Medawachchiya',
    'Tambuttegama',
    'Eppawala',
    'Mihintale',
    'Nochchiyagama',
    'Galenbindunuwewa',
    'Horowpothana',
    'Kahatagasdigiliya',
    'Padaviya',
    'Talawa',
    'Thirappane',
    'Rambewa',
    'Habarana',
    'Ipalogama',
    'Rajanganaya',
    'Galkiriyagama',
    'Andiyagala',
    'Galkadawala',
    'Kebithigollewa',
    'Mahavilachchiya',
    'Saliyapura',
    'Maradankadawala',
  ]),

  ...createCities('POLONNARUWA', [
    'Polonnaruwa',
    'Hingurakgoda',
    'Medirigiriya',
    'Kaduruwela',
    'Dimbulagala',
    'Bakamuna',
    'Manampitiya',
    'Welikanda',
    'Aralaganwila',
    'Lankapura',
    'Giritale',
    'Minneriya',
    'Jayanthipura',
    'Elahera',
    'Siripura',
    'Gallella',
    'Kalinga Ela',
    'Sewanapitiya',
    'Onegama',
    'Pulastigama',
    'Unagalawehera',
    'Jayapura',
  ]),

  ...createCities('KURUNEGALA', [
    'Kurunegala',
    'Kuliyapitiya',
    'Narammala',
    'Wariyapola',
    'Pannala',
    'Mawathagama',
    'Polgahawela',
    'Ibbagamuwa',
    'Nikaweratiya',
    'Galgamuwa',
    'Melsiripura',
    'Alawwa',
    'Hettipola',
    'Bingiriya',
    'Dambadeniya',
    'Giriulla',
    'Mallawapitiya',
    'Maho',
    'Kobeigane',
    'Pothuhera',
    'Boyagane',
    'Wewagama',
    'Pilessa',
    'Yapahuwa',
    'Ambanpola',
    'Moragollagama',
    'Rideegama',
    'Udubaddawa',
    'Gokarella',
    'Polpithigama',
    'Rasnayakapura',
  ]),

  ...createCities('PUTTALAM', [
    'Puttalam',
    'Chilaw',
    'Wennappuwa',
    'Nattandiya',
    'Marawila',
    'Dankotuwa',
    'Anamaduwa',
    'Kalpitiya',
    'Mundel',
    'Madampe',
    'Arachchikattuwa',
    'Mahawewa',
    'Waikkal',
    'Kakkapalliya',
    'Norochcholai',
    'Palavi',
    'Karuwalagaswewa',
    'Madurankuliya',
    'Nainamadama',
    'Toppuwa',
    'Udappuwa',
    'Serukele',
    'Eluwankulama',
  ]),

  ...createCities('KEGALLE', [
    'Kegalle',
    'Mawanella',
    'Warakapola',
    'Rambukkana',
    'Ruwanwella',
    'Deraniyagala',
    'Dehiowita',
    'Yatiyantota',
    'Galigamuwa',
    'Aranayake',
    'Bulathkohupitiya',
    'Devalegama',
    'Nelundeniya',
    'Hemmathagama',
    'Tholangamuwa',
    'Morontota',
    'Pindeniya',
    'Kitulgala',
    'Dedigama',
    'Ussapitiya',
    'Hingula',
    'Ambepussa',
    'Algama',
  ]),

  ...createCities('RATNAPURA', [
    'Ratnapura',
    'Balangoda',
    'Embilipitiya',
    'Pelmadulla',
    'Eheliyagoda',
    'Kuruwita',
    'Kahawatta',
    'Rakwana',
    'Godakawela',
    'Kalawana',
    'Nivitigala',
    'Ayagama',
    'Opanayake',
    'Pallebedda',
    'Weligepola',
    'Kolonna',
    'Eratna',
    'Marapana',
    'Panamure',
    'Kiriella',
    'Elapatha',
    'Dodampe',
    'Malwala',
    'Hidellana',
  ]),

  ...createCities('BADULLA', [
    'Badulla',
    'Bandarawela',
    'Ella',
    'Haputale',
    'Welimada',
    'Mahiyanganaya',
    'Passara',
    'Hali Ela',
    'Diyatalawa',
    'Lunugala',
    'Meegahakiula',
    'Kandaketiya',
    'Uva Paranagama',
    'Soranatota',
    'Kahataruppa',
    'Bogahakumbura',
    'Ettampitiya',
    'Haldummulla',
    'Dambana',
    'Kumbalwela',
    'Demodara',
    'Namunukula',
    'Koslanda',
  ]),

  ...createCities('MONARAGALA', [
    'Monaragala',
    'Wellawaya',
    'Bibile',
    'Buttala',
    'Kataragama',
    'Medagama',
    'Siyambalanduwa',
    'Thanamalwila',
    'Badalkumbura',
    'Madulla',
    'Okkampitiya',
    'Dambagalla',
    'Sevanagala',
    'Kumbukkana',
    'Kotagama',
    'Nakkala',
    'Ettiliwewa',
    'Galabedda',
    'Maligawila',
    'Sellakataragama',
    'Kiriibbanwewa',
    'Hulandawa',
  ]),
] as const;

async function main() {
  const provinceIdsByCode = new Map<string, string>();
  const districtIdsByCode = new Map<string, string>();

  for (const province of sriLankanProvinces) {
    const savedProvince = await prisma.province.upsert({
      where: {
        code: province.code,
      },
      update: {
        name: province.name,
        displayOrder: province.displayOrder,
        isActive: true,
      },
      create: {
        name: province.name,
        code: province.code,
        displayOrder: province.displayOrder,
        isActive: true,
      },
    });

    provinceIdsByCode.set(province.code, savedProvince.id);
  }

  for (const district of sriLankanDistricts) {
    const provinceId = provinceIdsByCode.get(district.provinceCode);

    if (!provinceId) {
      throw new Error(
        `Province "${district.provinceCode}" not found for district "${district.name}"`,
      );
    }

    const savedDistrict = await prisma.district.upsert({
      where: {
        code: district.code,
      },
      update: {
        name: district.name,
        provinceId,
        displayOrder: district.displayOrder,
        isActive: true,
      },
      create: {
        name: district.name,
        code: district.code,
        provinceId,
        displayOrder: district.displayOrder,
        isActive: true,
      },
    });

    districtIdsByCode.set(district.code, savedDistrict.id);
  }

  for (const city of sriLankanCities) {
    const districtId = districtIdsByCode.get(city.districtCode);

    if (!districtId) {
      throw new Error(
        `District "${city.districtCode}" not found for city "${city.name}"`,
      );
    }

    await prisma.city.upsert({
      where: {
        code: city.code,
      },
      update: {
        name: city.name,
        districtId,
        displayOrder: city.displayOrder,
        isActive: true,
      },
      create: {
        name: city.name,
        code: city.code,
        districtId,
        displayOrder: city.displayOrder,
        isActive: true,
      },
    });
  }

  console.log(
    `Seeded ${sriLankanProvinces.length} Sri Lankan provinces successfully.`,
  );
  console.log(
    `Seeded ${sriLankanDistricts.length} Sri Lankan districts successfully.`,
  );
  console.log(
    `Seeded ${sriLankanCities.length} Sri Lankan cities successfully.`,
  );
}

main()
  .catch((error) => {
    console.error('Province/District/City seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
